name: counter_app
description: A Counter App.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^2.0.0
  bloc: ^7.0.0
  cupertino_icons: ^1.0.0
  device_preview: ^0.7.1
  flare_flutter: ^3.0.0
  flutter_bloc: ^7.0.0
  hydrated_bloc: ^7.0.0
  simple_animations: ^3.1.1
  sizer: ^2.0.13
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/flares/

flutter_icons:
  android: true
  image_path: "assets/icon-512x512.png"
